json.id client.id
json.name client.name
json.last_name client.last_name
json.email client.email
json.b_date client.b_date
json.status client.status
json.contact_means client.contact_means
json.phone client.phone
json.address client.address
json.personal_description client.personal_description